var languages = {
    "JP":{
        "overview":"作品概要",
        "indent":" 週刊少年ジャンプにて連載していた 岸本斉史による少年漫画。<br>1999年の連載開始からまたたく間に人気を博し、<br>2002年よりTVアニメーションを放送開始。<br>2014年に700回をもって連載終了。完結後もイベント、ゲーム、グッズなどが発売され続ける国民的作品。<br>海外からの評価も高く、発行部数は全世界累計2億5000万部を突破、<br>2006年にはニューズウィーク日本版の特集「世界が尊敬する日本人100人」に主人公、<br>うずまきナルトが架空の人物として唯一選出される。現在は続編である[BORUTO-ボルト- -NARUTO NEXT GENERATIONS-]<br>（監修：岸本斉史 漫画：池本幹雄）がVジャンプにて連載中。壮大な物語を体験せよ！",
        "text":"<h2>NARUTO</h2>忍の里・木ノ葉隠れの里の少年・うずまきナルトは忍者学校の超問題児。<br>毎日いたずらばかりして、イルカ先生に怒られている。その上、<br>学校では落ちこぼれで卒業もおぼつかない。だがナルトには、<br>里の忍びの長・火影の名をついで、里一番の忍者になるという夢があった。<br>しかし、そんなナルトを見る里の大人たちの視線は冷たい。<br>実はナルトには出生の秘密があった。12年前に里を苦しめた「九尾の妖狐」が、当時赤子だったナルトの身に封印されていたのだ。学校の教官・<br>ミズキに利用されて、火影のもとから「封印の書」を盗み出したナルトは、<br>再び現れたミズキにそのことを知らされ、がく然とする。イルカの助けもあって、<br>ナルトは間一髪ミズキを倒す。ナルトの秘密を知りながらも、<br>イルカがナルトのよき理解者であったことを悟り、ナルトは決意を新たにするのだった。<br>無事忍者学校の卒業を許されたナルトは、同じ生徒のうちはサスケ、春野サクラとともに、<br>忍者としての第一歩を踏み出す！",
        "boruto-text":"世界を揺るがし、多くの血が流れた忍界大戦もすでに過去。うずまきナルトが七代目火影となり、木の葉隠れの里の人々も平和を享受する時代。ナルトの息子・うずまきボルトは、偉大すぎる父の影響からか鬱屈した日々を送っていた。<br> ナルトに反発しつつも認めてほしいボルトは、スリーマンセルを組むサラダとミツキと共に「中忍試験」を受けることに。その過程でボルトは、サラダの父でありナルトのライバルであったサスケに弟子入りし、忍術の修行を開始する。<br>しかし試験はボルトが想像するより厳しいものであった。ボルトは禁止されている科学忍具を密かに使ってしまい…。そして彼らの気づかぬところで、新たな災いが忍び寄るのだが…。伝説の忍者の子供達が今、新たな忍道を歩む!!",
        "news-1":"筆者は、数年間アメリカ・ロサンゼルスで暮らしたことがありますが、現地の友人たちは、例えばアクロバティックな大道芸を見ては、「Wow! Ninja!!」",
        "news-2":"ナルト走り」でプロのランナーが50mを全力疾走すると？ 三津家貴也が“忍の走法”で最速を目指す",
        "news-3":"チャクラ、増やしましょう。『NARUTO-ナルト-』の「兵糧丸」を小林銅蟲が再現してみた",
        "news-4":"我愛羅に憧れていたので、あの「ひょうたん」をリュックにして持ち歩いてみた",
        "footer-text":"このサイトは機械翻訳を導入しています。わかりにくい表現があるかもしれませんが、ご了承ください。お住まいの地域によっては掲載情報が異なる場合がございます。情報は掲載時点のものとなります。",
    },
    "FR":{
        "overview":"APERÇU DE L’ŒUVRE",
        "indent":"Naruto est un manga de type shônen créé parMasashi Kishimoto et qui a été publié dans leWeekly Shônen Jump.La publication originale a débuté en 1999et forte de son succès, la série a été adaptéeen dessin animé à partir de 2002.<br><br>Le manga s’est terminé en 2014 avec un total de 700 chapitreset plus de 250 millions de mangas imprimés vendus dans le monde.Malgré sa conclusion, la série a toujours une grande influenceau Japon, et les événements, les jeux et les produits dérivéscontinuent de se vendre encore aujourd’hui.<br><br>La suite de la série Naruto, BORUTO -NARUTO NEXT GENERATIONS-(supervision : Masashi Kishimoto, dessin : Mikio Ikemoto), est actuellement publiée dans le V Jump. Découvrez la nouvellegénération dès maintenant !",
        "text":"<h2>NARUTO</h2>Jeune garçon vivant au village de Konoha, Naruto Uzumaki est le pire garnement de l’académie des ninjas. À force de faire tous les jours les quatre cents coups, il se fait constamment réprimander par maître Iruka. Pas doué à l’école, il rate plusieurs fois l’examen de genin. Mais Naruto a un rêve démesuré : devenir le plus puissant ninja de son village, en devenant le nouvel Hokage, le chef de Konoha.<br> Cependant, il n’est pas apprécié par les adultes du village en raison du secret de sa naissance. Il y a 12 ans, alors que Naruto n’était qu’un bébé, Kyûbi, le Démon-Renard à Neuf Queues qui a soudainement attaqué le village, a été scellé en lui.  Ce fait lui est révélé par Mizuki, instructeur de l’académie qui utilise Naruto pour voler le rouleau des techniques interdites de l’actuel Hokage.Naruto parvient à vaincre Mizuki avec l’aide d’Iruka, qui, bien que connaissant le passé de Naruto, a toujours cru en lui. Naruto en ressort d’autant plus décidé à poursuivre son rêve. Après avoir obtenu son diplôme de l’académie aux côtés de ses camarades Sasuke Uchiwa et Sakura Haruno, Naruto fait enfin ses premiers pas en tant que véritable ninja !",
        "boruto-text":"La Grande Guerre Ninja, qui a secoué le monde et fait couler beaucoup de sang, appartient désormais au passé. Le village de Konoha est entré dans une ère de paix et Naruto est devenu le Septième Hokage. Mais son fils, Boruto, vit mal d’être dans l’ombre de son éminent paternel.<br>En conflit avec lui tout en cherchant sa reconnaissance en tant que shinobi, Boruto fait équipe avec Sarada et Mitsuki pour passer les examens de sélection des chûnin.<br>Il devient par la même occasion l’apprenti de Sasuke, père de Sarada et ancien rival de Naruto, qui l’initie au ninjutsu.Cependant, les examens sont beaucoup plus durs que Boruto ne l’avait imaginé, poussant ce dernier à utiliser des artefacts de l’unité scientifique pourtant interdits…<br>Il ne se doute pas qu’une nouvelle menace plane sur eux… La légende de la nouvelle génération commence maintenant !!",
        "news-1":"Pourquoi les ninjas sont si populaires à l'étranger ? On a posé la question au légendaire acteur ninja d’Hollywood Sho Kosugi et à un spécialiste de la littérature américaine !",
        "news-2":"Que se passe-t-il lorsqu'un coureur professionnel parcourt 50 mètres à toute vitesse avec le « Naruto Run » ? Takaya Mitsuka espère bien être le plus rapide avec ce « style de course des ninjas » !",
        "news-3":"Augmentons notre chakra ! Kobayashi Doom recrée les « hyôrôgan » de NARUTO",
        "news-4":"Par admiration pour Gaara, j’ai essayé de porter sa jarre comme un sac à dos",
        "footer-text":"Ce site Internet utilise en partie la traduction automatique. Veuillez noter que certaines expressions peuvent être difficiles à comprendre.<br>Les informations figurant sur ce site peuvent varier en fonction de votre position géographique.Elles sont valables au moment de la publication."
    },
    "DE":{
        "overview":"ÜBERSICHT",
        "indent":"NARUTO ist ein Manga von Masashi Kishimoto,der im japanischen Manga-Magazin WEEKLY JUMP erschien.<br> Die erstmalige Veröffentlichung erfolgte im Jahr 1999 und nachdem sich der Manga a großer Popularität erfreute,<br>wurde er als Anime adaptiert und 2002 erstmals ausgestrahlt. Die Geschichte fand ihr Finale im Jahre 2014 nach 700 Kapiteln. Naruto bleibt auch heute beliebt und Fans erfreuen sich weiterhin an Events, Spielen und Merchandise.<br><br>Auch weltweit genießt der Manga mit einer Gesamtauflage vonmehr als 250 Millionen Exemplaren große Beliebtheit und im Jahre 2006 wurde Naruto Uzumaki sogar als einzige fiktive Persönlichkeit von dem japanischen Magazin Newsweek in die Liste der “Weltweit 100 meistrespektierten Japaner” aufgenommen.<br><br>Die Fortsetzung, “Boruto: Naruto Next Generations” (Leitung: Masashi Kishimoto, Manga: Mikio Ikemoto), wird derzeit im Manga-Magazin V Jump veröffentlicht. Erlebt die epische Geschichte!",
        "text":"<h2>NARUTO</h2>Naruto Uzumaki, ewiges Sorgenkind der Ninja-Akademie, ist ein Ninja aus dem Dorf Konoha. Tagtäglich sorgt er für Randale und wird dafür von seinem Lehrer, Iruka Umino, zurechtgewiesen. Darüber hinaus steht sein Abschluss von der Ninja-Akademie auf der Kippe, dennoch ist es Narutos Traum, das Oberhaupt des Dorfs, Hokage, und der größte Shinobi aller Zeiten zu werden.<br>Von den Älteren des Dorfs wird Naruto jedoch nur verachtet, denn er trägt seit seiner Geburt ein Geheimnis mit sich.<br>Vor 12 Jahren, als Naruto noch ein Baby war, attackierte ein neunschwänziger Fuchs das Dorf und konnte nur aufgehalten werden, indem er in Narutos Körper versiegelt wurde. Mizuki, ein Lehrer der Akademie, benutzt Naruto, um eine geheime Schriftrolle vom Hokage zu stehlen und offenbart ihm die schockierende Wahrheit über seine Geburt.<br>Mithilfe von Iruka kann Naruto Mizuki besiegen und Iruka, der trotz Narutos Geheimnis diesen immer unterstützt hat, gibt Naruto neue Hoffnung und Motivation, seinen Traum zu verfolgen. Nachdem er schließlich erfolgreich die Ninja-Akademie abschließen kann, beginnt Naruto seine ersten Abenteuer gemeinsam mit seinen Schulkameraden Sasuke Uchiha und Sakura Haruno! ",
        "boruto-text":"Der große Shinobi-Weltkrieg, in dem Unmengen an Blut vergossen wurden, gehört der Vergangenheit an. Naruto Uzumaki ist der 7. Hokage und in Konoha herrscht Frieden. Narutos Sohn, Boruto Uzumaki, lebt im Schatten seines großen Vaters.<br>Obwohl er gegen seinen Vater rebelliert, hofft er insgeheim doch, dessen Anerkennung gewinnen zu können und so tritt Boruto in einem 3er-Team gemeinsam mit seinen Freunden Sarada und Mitsuki die Chunin-Prüfung an.<br>Deshalb beginnt er auch das Training und wird Schüler von niemand anderem als Saradas Vater und Narutos ehemaligem Rivalen, Sasuke.<br>Doch die Prüfung erweist sich für Boruto schwerer als erwartet und so greift er zu verbotenen Mitteln … Währenddessen braut sich ohne, dass es jemand bemerkt, bereits eine neue Bedrohung über dem Horizont der tapferen Shinobi auf …!<br>Die Nachkommen der legendären Ninja treten ihren eigenen Ninja-Weg an!",
        "news-1":"Warum sind Ninja außerhalb von Japan so populär? Wir fragen den legendären Hollywood-Ninja-Darsteller Sho...",
        "news-2":"Was passiert, wenn ein professioneller Läufer mit dem \"Naruto-Laufstil\" 50 Meter mit voller Geschwindigkeit läuft?",
        "news-3":"Lasst uns unser Chakra erhöhen! Doom Kobayashi hat für uns die Hyourougan-Pillen aus NARUTO nachgekocht",
        "news-4":"Ich bewundere Gaara so sehr, dass ich seine \"Kürbisflasche\" zu einem Rucksack machte und ihn mit mir herumtrug",
        "footer-text":"Diese Seite wurde maschinell übersetzt. Dadurch kann es dazu kommen, dass einige Ausdrücke/Sätze schwer verständlich sind. Wir bitten um Verständnis.<br>Die Informationen auf dieser Webseite können sich je nach Standort unterscheiden.<br>Die Informationen entsprechen dem Stand zum Zeitpunkt der Veröffentlichung."
    },
    "ES":{
        "overview":"INFORMACIÓN GENERAL",
        "indent":"NARUTO es un manga de Masashi Kishimoto que fue serializado en la revista japonesa de manga WEEKLY SHONEN JUMP.<br>Se publicó por primera vez en 1999 y, después de que el manga gozara de gran popularidad, se adaptó al anime y se emitió por primera vez en 2002.<br>La historia llegó a su final en 2014 después de 700 capítulos y más de 250 millones de copias vendidas. NARUTO sigue siendo popular hoy en día y los fans continúan disfrutando de nuevos eventos, juegos y productos. La secuela, “BORUTO: Naruto Next Generations”  (director: Masashi Kishimoto, manga: Mikio Ikemoto), se está publicando actualmente en la revista de manga V Jump. ¡Vive una historia épica!",
        "text":"<h2>NARUTO</h2>Naruto Uzumaki, el eterno niño problemático de la Academia Ninja, es un ninja de la aldea de Konoha. Se mete en problemas todos los días y su maestro, Iruka Umino, no para de regañarle. Además, mientras su graduación de la Academia Ninja está a la vista, el sueño de Naruto es convertirse en Hokage, el líder de la aldea, y en el ninja más grande de todos los tiempos.<br>Sin embargo, Naruto es despreciado por los ancianos de la aldea porque ha estado guardando un secreto desde su nacimiento.<br><br>Hace 12 años, cuando Naruto era solo un bebé, un Zorro de Nueve Colas atacó la aldea y solo pudo ser detenido al ser sellado en el cuerpo de Naruto.<br>Mizuki, un maestro de la Academia, usa a Naruto para robar un pergamino secreto del Hokage y revela la impactante verdad sobre el nacimiento de Naruto.<br>Con la ayuda de Iruka, Naruto consigue derrotar a Mizuki, e Iruka, quien siempre ha apoyado a Naruto a pesar de su secreto, le da a Naruto una nueva esperanza y motivación para perseguir su sueño.<br>Después de graduarse finalmente con éxito de la Academia Ninja, ¡Naruto comienza sus primeras aventuras con sus compañeros de clase, Sasuke Uchiha y Sakura Haruno!",
        "boruto-text":"La Gran Guerra Ninja, en la que se derramó mucha sangre, es cosa del pasado. Naruto Uzumaki es el Séptimo Hokage y la aldea de Konoha disfruta de una era de paz. El hijo de Naruto, Boruto Uzumaki, vive estancado bajo la sombra de su eminente padre. Aunque se rebela contra él, en secreto espera obtener su aprobación, por lo que Boruto participa en el examen de Chunin en un equipo de tres junto con sus amigos Sarada y Mitsuki. De esta manera, comienza a entrenar y se convierte en alumno de nada menos que el padre de Sarada y antiguo rival de Naruto, Sasuke.<br>Pero la prueba resulta ser más difícil de lo esperado para Boruto, que recurre a herramientas científicas ninja prohibidas… Mientras tanto, sin que nadie se diera cuenta, ¡una nueva amenaza ya se estaba gestando en el horizonte! ¡Los descendientes de legendarios ninjas comienzan a formar su propio camino!",
        "news-1":"¿Por qué los ninjas son famosos en el mundo? ¡Se lo preguntamos a Sho Kosugi, un actor ninja legendario de Hollywood...",
        "news-2":"¿Qué pasa si un corredor profesional corre 50 metros como Naruto con todas sus fuerzas?...",
        "news-3":"¡Aumentemos el chakra! Kobayashi Doom intenta recrear las “píldoras de soldado” de NARUTO...",
        "news-4":"Soy fanática de Gaara, así que fabriqué una mochila con la forma de su calabaza",
        "footer-text":"Este sitio web utiliza herramientas de traducción automática. Es posible que algunos textos resulten difíciles de comprender.<br>El contenido que aparece en este sitio web podría cambiar según la región en la que te encuentres.<br>La información mostrada en este sitio refleja la situación del momento en que fue publicada."
    },
    "IT":{
        "overview":"CENNI GENERALI",
        "indent":"Un manga di Masashi Kishimoto, comparso su Weekly Shonen Jump. Pubblicato a partire dal 1999, il suo enorme successo ha portato alla nascita dell’ anime nel 2002. Termina nel 2014, dopo 700 capitoli. Vanta 250 milioni di copie vendute in tutto il mondo, oltre a tutta una serie di gadget, videogiochi ed eventi a tema creati ancor oggi.Vi è anche un sequel, “BORUTO: Naruto Next Generation” (supervisione: Masashi Kishimoto; disegni: Mikio Ikemoto), pubblicato su V Jump. Cosa aspetti? Tuffati anche tu nel mondo di NARUTO!",
        "text":"<h2>NARUTO</h2>Konoha, il villaggio della foglia, è il luogo dove risiede Naruto Uzumaki, studente dell’ accademia ninja e noto piantagrane. A dispetto dei suoi voti bassissimi, il ragazzo ha un sogno: diventare Hokage, ovvero il miglior ninja del villaggio. Un sogno impossibile da realizzare, considerando che gli abitanti del villaggio non  vedono in lui altro che il ragazzo in cui è sigillata la volpe a nove code, un terribile demone che attaccò il villaggio 12 anni prima. Questo terribile segreto sarà rivelato a Naruto da Mizuki, un maestro dell’ accademia  che cerca di sfruttare il ragazzo per i suoi loschi piani, convincendolo a intrufolarsi nella dimora dell’ Hokage e rubare il cosiddetto “rotolo proibito” custodito al suo interno.<br> Aiutato dal maestro Iruka, il quale riesce ad andare oltre le apparenze e vedere Naruto per ciò che realmente è, il giovane ninja riesce a sconfiggere Mizuki per un soffio e a trovare il coraggio per inseguire il suo sogno.<br> Ottenuta la tanto agognata promozione, Naruto, affiancato dai nuovi compagni Sasuke Uchiha e Sakura Haruno, è pronto a compiere i suoi primi passi nel mondo dei ninja.",
        "boruto-text":"Siamo di nuovo a Konoha. La guerra mondiale ninja non è che un ricordo lontano, e, grazie al settimo Hokage Naruto Uzumaki, la vita nel villaggio scorre tranquilla. Boruto, figlio di Naruto, è un giovane ninja<br> che cerca in tutti i modi di uscire dall’ ombra di suo padre. Per ottenerne l’ approvazione, decide di formare una squadra con cui partecipare all’ esame Chunin e di farsi allenare da Sasuke, rivale di suo padre e a sua volta padre di Sarada, una sua amica. L’ esame, tuttavia, si rivela più difficile del previsto, e ciò spinge Boruto a violare le regole e usare gli attrezzi ninja scientifici. Nel frattempo, una nuova minaccia si avvicina silenziosa a Konoha…<br>È sull’ onda di questi eventi che la nuova generazione di shinobi si troverà a scegliere il proprio credo ninja e tracciare il proprio destino!",
        "news-1":"Perché il mondo ama i ninja? A darci la risposta, il leggendario attore di Hollywood...",
        "news-2":"Un velocista professionista fa uno sprint di 50 metri di \"Corsa alla NARUTO\"!?...",
        "news-3":"Aumentiamo il Chakra! Kobayashi Doom ai fornelli per il tonico da guerra di NARUTO!",
        "news-4":"Adoravo così tanto Gaara che mi sono fatta uno zaino simile alla sua \"zucca\"",
        "footer-text":"Questo sito fa uso parziale di traduzione automatica. Alcune espressioni potrebbero non essere perfettamente comprensibili.<br>I contenuti presenti sul sito potrebbero variare in base alla vostra regione.<br>Tutte le notizie risultano attendibili al momento della pubblicazione."
    }
};
const language = document.getElementById('select1');
language.addEventListener('click',function(){
    
    const lang = String(language.value);
    const list = languages[lang];
    for(let key in list){
        document.querySelector(`.${key}`).innerHTML=list[key];
    } 
}); 
 

